language: node_js
node_js:
  - "6.11.4"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project mikkipastel --token $FIREBASE_TOKEN
